File duplication

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -28,8 +28,22 @@ jobs:
       # Runs a single command using the runners shell
       - name: Run a one-line script
         run: echo Hello, world!
-      - name: My own step
-        run: echo Hello, I am here on my Own
+        
+      - name: List Files in folder
+        run: ls -la
+
+      - name: Duplicate jindex java
+        run: |
+          if[ -f 'jindex java' ]; then
+            cp 'jindex java' index.java
+            echo "file duplicated"
+          else
+            echo "File not found"
+            exit 1
+          fi
+
+      - name: File check
+        run: ls -la
         
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
